version: "3"
services:
   domain_refresher:
      build: .
      restart: always
      volumes:
          - ./config.json:/home/refresher/target/release/config.json
          - /etc/timezone:/etc/timezone
